// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PackageInstaller
{
    internal sealed partial class Vsix
    {
        public const string Id = "6ffd6f4d-bbe0-489a-8f6a-33f440773f14";
        public const string Name = "Package Installer";
        public const string Description = @"Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project";
        public const string Language = "en-US";
        public const string Version = "2.2.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "npm, bower, jspm, nuget, tsd, DefinitelyTyped, Yarn";
    }
}
