// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PackageInstaller
{
    static class Vsix
    {
        public const string Id = "fdd64809-376e-4542-92ce-808a8df06bcc";
        public const string Name = "Package Installer";
        public const string Description = @"Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "npm, bower, jspm, nuget, tsd, DefinitelyTyped, Yarn";
    }
}
